<?
$aSearchFileds = array(
    array(	'name' => 'lstCountry',
    		'empty' => 'All',
    		'emptyset'=>0,
    		'table' => 'geo_country'
    		),
    array(	'name' => 'lstState',
    		'empty' => '0',
    		'emptyset'=>0,
    		'table' => 'geo_state'
    		),
    array(	'name' => 'lstCity',
    		'empty' => '0',
    		'emptyset'=>0,
    		'table' => 'geo_city'
    		),
    array(	'name' => 'lstSeeking',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_SEEKING',
    		'option'=>'SKG',
    		'label' => 'OPTION_SEEKING'
    		),
    array(	'name' => 'lstBodyType',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_BODYTYPE',
    		'option'=>'BDY',
    		'label' => 'OPTION_BODY_TYPE'
    		),
    array(	'name' => 'lstMarital',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_MARITAL',
    		'option'=>'MRT',
    		'label' => 'OPTION_MARITAL'
    		),
    array(	'name' => 'lstEyecolor',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_EYECOLOR',
    		'option'=>'EYE',
    		'label' => 'OPTION_EYE_COLOR'
    		),
    array(	'name' => 'lstHaircolor',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_HAIRCOLOR',
    		'option'=>'HAR',
    		'label' => 'OPTION_HAIR_COLOR'
    		),
    array(	'name' => 'lstEthnicity',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_ETHNICITY',
    		'option'=>'ETH',
    		'label' => 'OPTION_ETHNICITY'
    		),
    array(	'name' => 'lstSmoker',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_SMOKER',
    		'option'=>'SMK',
    		'label' => 'OPTION_SMOKER'
    		),
    array(	'name' => 'lstDrink',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_DRINK',
    		'option'=>'DNK',
    		'label' => 'OPTION_DRINK'
    		),
    array(	'name' => 'lstReligion',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_RELIGION',
    		'option'=>'RLG',
    		'label' => 'OPTION_RELIGION'
    		),
    array(	'name' => 'lstChildren',
    		'empty' => '- Any -',
    		'emptyset' => '- Any -',
    		'table' => 'adverts',
    		'field'=>'ADV_CHILDREN',
    		'option'=>'CHL',
    		'label' => 'OPTION_CHILDREN'
    		),
);
?>